# Generated by Django 5.1.3 on 2024-11-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_share', '0003_platform_base_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(choices=[('semrush', 'Semrush'), ('keywords_tool', 'Keywords Tool'), ('canva', 'Canva'), ('freepik', 'FreePik'), ('minea', 'Minea'), ('placeit', 'Placeit'), ('pipi_ads', 'Pipi Ads'), ('heyesty', 'Heyesty'), ('dropship', 'Dropship'), ('auto_ds', 'Auto DS')], default='semrush', max_length=100),
        ),
    ]
