# Generated by Django 5.1.3 on 2024-12-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_share', '0004_alter_platform_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='base_path',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='blacklist_path',
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
