# Generated by Django 5.1.3 on 2024-12-05 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_share', '0007_platformaccount_login_platformaccount_login_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformaccount',
            name='login_method',
        ),
        migrations.RemoveField(
            model_name='platformaccount',
            name='user',
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='user',
            field=models.ManyToManyField(related_name='platform_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
