# Generated by Django 5.1.3 on 2024-12-05 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_share', '0008_remove_platformaccount_login_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformaccount',
            name='user',
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='users',
            field=models.ManyToManyField(related_name='platform_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
    ]
