# Generated by Django 5.1.3 on 2024-12-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('address', models.CharField(max_length=200, verbose_name='Địa chỉ')),
            ],
            options={
                'verbose_name': 'Thông tin quản trị',
                'verbose_name_plural': 'Thông tin quản trị',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20, verbose_name='Nền tảng mạng xã hội')),
                ('url', models.URLField(verbose_name='Đường dẫn')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
            ],
            options={
                'verbose_name': 'Liên kết mạng xã hội',
                'verbose_name_plural': 'Liên kết mạng xã hội',
            },
        ),
        migrations.CreateModel(
            name='LandingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_cover_image', models.ImageField(blank=True, null=True, upload_to='landing/covers/', verbose_name='Ảnh bìa header')),
                ('header_title', models.CharField(max_length=200, verbose_name='Tiêu đề header')),
                ('header_description', models.TextField(verbose_name='Mô tả header')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_links', models.ManyToManyField(blank=True, to='landing.sociallink', verbose_name='Liên kết mạng xã hội')),
            ],
            options={
                'verbose_name': 'Nội dung Landing Page',
                'verbose_name_plural': 'Nội dung Landing Page',
            },
        ),
    ]
