# Generated by Django 5.1.4 on 2024-12-17 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_alter_sociallink_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='icon',
        ),
    ]
