# Generated by Django 5.1.4 on 2024-12-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_remove_sociallink_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('url', models.CharField(max_length=200, verbose_name='Đường dẫn')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_cover_image', models.ImageField(blank=True, null=True, upload_to='landing/covers/', verbose_name='Ảnh bìa header')),
                ('header_title', models.CharField(max_length=200, verbose_name='Tiêu đề header')),
                ('header_description', models.TextField(verbose_name='Mô tả header')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
            ],
            options={
                'verbose_name': 'Tiêu đề',
                'verbose_name_plural': 'Tiêu đề',
            },
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='social_links',
        ),
        migrations.CreateModel(
            name='Footer_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('links', models.ManyToManyField(to='landing.footer_link', verbose_name='Danh sách đường dẫn')),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('list_of_links', models.ManyToManyField(to='landing.footer_list', verbose_name='Danh sách chân trang')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
    ]
