# Generated by Django 5.1.4 on 2024-12-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_footer_link_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontent',
            name='document_url',
            field=models.URLField(blank=True, null=True, verbose_name='Đường dẫn tài liệu sử dụng'),
        ),
    ]
