# Generated by Django 5.1.4 on 2024-12-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_landingpagecontent_document_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Footer_list',
            new_name='FooterColumn',
        ),
        migrations.RenameModel(
            old_name='Footer_link',
            new_name='FooterLink',
        ),
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
