# Generated by Django 5.1.4 on 2024-12-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_rename_footer_list_footercolumn_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footercolumn',
            options={'verbose_name': 'Cột chân trang', 'verbose_name_plural': 'Cột chân trang'},
        ),
        migrations.AlterModelOptions(
            name='footerlink',
            options={'verbose_name': 'Đường dẫn chân trang', 'verbose_name_plural': 'Đường dẫn chân trang'},
        ),
        migrations.AlterField(
            model_name='footercolumn',
            name='links',
            field=models.ManyToManyField(to='landing.footerlink', verbose_name='Danh sách url'),
        ),
    ]
