# Generated by Django 5.1.3 on 2024-12-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_coupon_is_public_alter_coupon_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên mã giảm giá'),
        ),
    ]
