# Generated by Django 5.1.4 on 2024-12-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_coupon_created_at_coupon_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Giảm giá (phần trăm)'),
        ),
    ]
