'''
Django settings for sharer project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
'''

from pathlib import Path
import os
from datetime import timedelta
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.templatetags.static import static
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=^v2tvlr5fkidj%u1=c&=1ch4%7v19x)n5m9ychszs=q5+-vj-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
PRODUCTION_ENABLED = True

CORS_ALLOW_ALL_ORIGINS = True 
ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    'http://160.187.246.140/',
    'https://160.187.246.140/',
    'https://app.toolsngon.com',
    "https://toolsngon.com/"
] 
SESSION_COOKIE_SECURE=False
# Application definition

INSTALLED_APPS = [
    'daphne',
    'unfold',  # before django.contrib.admin
    'unfold.contrib.import_export',  # optional, if django-import-export package is used
    'import_export',
    'unfold.contrib.filters',  # optional, if special filters are needed
    'unfold.contrib.forms',  # optional, if special form elements are needed
    'unfold.contrib.inlines',  # optional, if special inlines are needed
    'unfold.contrib.guardian',  # optional, if django-guardian package is used
    'unfold.contrib.simple_history',  # optional, if django-simple-history package is used
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'channels',
    'custom_user',
    'subscriptions',
    'platforms',
    'landing',
    'orders',
    'sharer',
    'coupons',
    'issues'
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django.middleware.locale.LocaleMiddleware"
]

ROOT_URLCONF = 'sharer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'subscriptions.context_processors.subscriptions_context',
                'landing.context_processors.landing_context'
            ],
        },
    },
]

WSGI_APPLICATION = 'sharer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media setting
MEDIA_URL = '/media/'
if PRODUCTION_ENABLED:
    MEDIA_ROOT = '/var/www/sharer/media/'
else:
    MEDIA_ROOT = BASE_DIR / 'media'
    
# Cấu hình cho file tĩnh
STATIC_URL = '/static/'  # URL truy cập các file tĩnh
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Thư mục chứa các file tĩnh trong mã nguồn
]
STATIC_ROOT = '/var/www/sharer/static/'  # Thư mục chứa các file tĩnh đã thu thập trong môi trường sản phẩm


STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
#Cors settings 
CORS_ALLOW_ALL_ORIGINS = True  # Cho phép tất cả các nguồn truy cập vào API của bạn
#custom user model
AUTH_USER_MODEL = 'custom_user.CustomUser'


#unfold admin setting
UNFOLD = {
    'SITE_TITLE': 'Sharer Admin',
    'SITE_HEADER': 'Sharer Admin',
    'SITE_ICON':lambda request: static('logo.svg'),
        'SITE_FAVICONS': [
        {
            'rel': 'icon',
            'sizes': '32x32',
            'type': 'image/svg+xml',
            'href': lambda request: static('logo.svg'),
        },
    ],
     'COLORS': {
        'primary': {
            '50': '#eff6ff',
            '100': '#dbeafe',
            '200': '#c7d2fe',
            '300': '#a5b4fc',
            '400': '#818cf8',
            '500': '#6366f1',
            '600': '#4f46e5',
            '700': '#4338ca',
            '800': '#3730a3',
            '900': '#312e81',
            '950': '#1e1b4b',
        },
    },
    'SIDEBAR': {
        'show_all_applications': True,  
        'navigation': [
            {
                'items': [
                    # {
                    #     'title': _('Dashboard'),
                    #     'icon': 'dashboard',  # Supported icon set: https://fonts.google.com/icons
                    #     'link': reverse_lazy('admin:index'),
                    #     'permission': lambda request: request.user.is_superuser,
                    # },
                    {
                        'title': _('Người dùng'),
                        'icon': 'people',
                        'link': reverse_lazy('admin:custom_user_customuser_changelist'),
                        'permission': lambda request: request.user.is_superuser,
                    },
                    {
                        'title': _('Kế hoạch'),
                        'icon': 'stacks',
                        'link': reverse_lazy('admin:subscriptions_subscriptionplan_changelist'),
                        'permission': lambda request: request.user.is_superuser,
                    },
                    {
                        'title': _('Quản lý tài khoản'),
                        'icon': 'language',
                        'link': reverse_lazy('admin:platforms_platform_changelist'),
                        'permission': lambda request: request.user.is_superuser,
                    },
                    {
                        'title': _('Người dùng đăng ký'),
                        'icon': 'groups',
                        'link': reverse_lazy('admin:subscriptions_packagetoken_changelist'),
                        'permission': lambda request: request.user.is_superuser,
                    },
                    {
                        'title': _('Đơn hàng'),
                        'icon': 'list_alt',
                        'link': reverse_lazy('admin:orders_order_changelist'),
                        'permission': lambda request: request.user.is_superuser,
                    },
                    {
                        'title': _('Mã giảm giá'),
                        'icon': 'money',
                        'link': reverse_lazy('admin:coupons_coupon_changelist'),
                        'permission': lambda request: request.user.is_superuser,
                    },
                    {
                        'title': _('Nội dung Landing Page'),
                        'icon': 'article',
                        'link': reverse_lazy('admin:landing_landingpagecontent_changelist'),
                        'permission': lambda request: request.user.is_superuser,
                    },
                    {
                        'title': _('Cài đặt thanh toán'),
                        'icon': 'credit_card',
                        'link': reverse_lazy('admin:orders_paymentsetting_changelist'),
                        'permission': lambda request: request.user.is_superuser,
                    },
                    {
                        'title': _('Báo cáo vấn đề'),
                        'icon': 'credit_card',
                        'link': reverse_lazy('admin:issues_issue_changelist'),
                        'permission': lambda request: request.user.is_superuser,
                    },
                ],
            },
        ],
    },
    "TABS": [
         {
            "models": [
                "landing.landingpagecontent",
                "landing.sociallink",
                "landing.footercolumn",
            ],
            "items": [
                {
                    "title": _("Nội dung landing page"),
                    "link": reverse_lazy("admin:landing_landingpagecontent_changelist"),
                },
                {
                    "title": _("Liên kết mạng xã hội"),
                    "link": reverse_lazy("admin:landing_sociallink_changelist"),
                },
                {
                    "title": _("Cột chân trang"),
                    "link": reverse_lazy("admin:landing_footercolumn_changelist"),
                },
            ],
        },
        {
            "models": [
                "platforms.platform",
                "platforms.accountgroup",
                "platforms.account",
            ],
            "items": [
                {
                    "title": _("Nền tảng"),
                    "link": reverse_lazy("admin:platforms_platform_changelist"),
                },
                {
                    "title": _("Nhóm tài khoản"),
                    "link": reverse_lazy("admin:platforms_accountgroup_changelist"),
                },
                {
                    "title": _("Tài khoản"),
                    "link": reverse_lazy("admin:platforms_account_changelist"),
                },
            ],
        },
        {
            "models": [
                "subscriptions.subscriptionplan",
                "subscriptions.subscriptionplanduration",
                "subscriptions.subscriptiondurationfilter"
            ],
            "items": [
                {
                    "title": _("Kế hoạch"),
                    "link": reverse_lazy("admin:subscriptions_subscriptionplan_changelist"),
                },
                {
                    "title": _("Chi tiết kế hoạch"),
                    "link": reverse_lazy("admin:subscriptions_subscriptionplanduration_changelist"),
                },
                {
                    "title": _("Bộ lọc gói"),
                    "link": reverse_lazy("admin:subscriptions_subscriptiondurationfilter_changelist"),
                },
            ],
        },
    ],
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "en": "🇬🇧",
                "fr": "🇫🇷",
                "nl": "🇧🇪",
            },
        },
    },
}
LANGUAGES = (
    ("vi", _("Vietnamese")),
)
LOGIN_URL = '/login/'
LANGUAGE_CODE = "vi"

USE_I18N = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
}

# Optional: Configure JWT settings (expiration, etc.)
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=5),  # Thời gian hết hạn của access token
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),  # Thời gian hết hạn của refresh token
    'ROTATE_REFRESH_TOKENS': True,  # Cho phép làm mới refresh token
    'BLACKLIST_AFTER_ROTATION': True,  # Đưa token vào blacklist sau khi refresh
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,  # Sử dụng SECRET_KEY của Django để ký token
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
}



ASGI_APPLICATION = 'sharer.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],  # Đảm bảo Redis đang chạy trên cổng này
        },
    },
}


# Custom error handlers
handler404 = 'sharer.views.handler404'


# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Hoặc dùng console trong quá trình phát triển
EMAIL_HOST = 'smtp.larksuite.com'  # SMTP server, ví dụ Gmail
EMAIL_PORT = 587  # Port cho giao thức TLS
EMAIL_USE_TLS = True  # Sử dụng TLS (True nếu dùng cổng 587)
EMAIL_HOST_USER = 'support@toolsngon.com'  # Địa chỉ email của bạn
EMAIL_HOST_PASSWORD = 'ZUYFCpmM4uq2DUQz'  # Mật khẩu ứng dụng hoặc tài khoản email
DEFAULT_FROM_EMAIL = 'Sharer <support@toolsngon.com>'  # Email người gửi
