# Generated by Django 5.1.3 on 2024-12-07 19:21

import custom_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=custom_user.models.generate_random_token, max_length=64, unique=True),
        ),
    ]
