# Generated by Django 5.1.4 on 2024-12-17 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_alter_usertoken_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
