# Generated by Django 5.1.4 on 2024-12-21 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0005_remove_customuser_is_verified_verificationcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['is_staff'], 'verbose_name': 'Người dùng', 'verbose_name_plural': 'Người dùng'},
        ),
    ]
