# Generated by Django 5.1.4 on 2024-12-22 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0006_alter_customuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uuid', models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='UUID thiết bị')),
                ('is_active', models.BooleanField(default=False, verbose_name='Đang đăng nhập')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Đăng nhập lần cuối')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Phiên đăng nhập',
                'verbose_name_plural': 'Phiên đăng nhập',
                'ordering': ['-last_login'],
            },
        ),
    ]
