# Generated by Django 5.1.4 on 2024-12-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0007_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_used_trial',
            field=models.BooleanField(default=False, verbose_name='Đã sử dụng gói trial'),
        ),
    ]
