# Generated by Django 5.1.3 on 2024-12-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='accounts',
            field=models.ManyToManyField(related_name='packages', to='platforms.account'),
        ),
    ]
