# Generated by Django 5.1.3 on 2024-12-08 09:22

import subscriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_remove_package_owner_alter_package_buyers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagetoken',
            name='token',
            field=models.CharField(default=subscriptions.models.generate_random_token, max_length=64, unique=True),
        ),
    ]
