# Generated by Django 5.1.3 on 2024-12-08 14:52

import django.db.models.deletion
import subscriptions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_packagetoken_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetoken',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='packagetoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='packagetoken',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Ngày hết hạn'),
        ),
        migrations.AlterField(
            model_name='packagetoken',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.package', verbose_name='Gói đăng ký'),
        ),
        migrations.AlterField(
            model_name='packagetoken',
            name='token',
            field=models.CharField(default=subscriptions.models.generate_random_token, max_length=64, unique=True, verbose_name='Mã truy cập'),
        ),
        migrations.AlterField(
            model_name='packagetoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
    ]
