# Generated by Django 5.1.3 on 2024-12-11 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscriptionplan_level_alter_packagetoken_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='accounts',
        ),
    ]
