# Generated by Django 5.1.3 on 2024-12-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_remove_package_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
