# Generated by Django 5.1.3 on 2024-12-13 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_package_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-id'], 'verbose_name': 'Gói', 'verbose_name_plural': 'Gói'},
        ),
        migrations.AlterModelOptions(
            name='packagetoken',
            options={'verbose_name': 'Mã đăng ký', 'verbose_name_plural': 'Mã đăng ký'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['level'], 'verbose_name': 'Kế hoạch', 'verbose_name_plural': 'Kế hoạch'},
        ),
    ]
