# Generated by Django 5.1.3 on 2024-12-13 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_alter_package_options_alter_packagetoken_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='price',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='usage_time',
        ),
        migrations.CreateModel(
            name='SubscriptionPlanDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_in_months', models.PositiveIntegerField()),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='durations', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Thời hạn gói',
                'verbose_name_plural': 'Thời hạn gói',
                'ordering': ['duration_in_months'],
            },
        ),
    ]
