# Generated by Django 5.1.3 on 2024-12-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_remove_subscriptionplan_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplanduration',
            options={'ordering': ['duration'], 'verbose_name': 'Thời hạn gói', 'verbose_name_plural': 'Thời hạn gói'},
        ),
        migrations.RenameField(
            model_name='subscriptionplanduration',
            old_name='duration_in_months',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='subscriptionplanduration',
            old_name='price_per_month',
            new_name='price',
        ),
    ]
