# Generated by Django 5.1.3 on 2024-12-13 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_alter_subscriptionplanduration_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagetoken',
            options={'verbose_name': 'Mã đăng ký', 'verbose_name_plural': 'Mã đăng ký'},
        ),
        migrations.AddField(
            model_name='packagetoken',
            name='subscription_duration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplanduration', verbose_name='Thời hạn gói'),
        ),
    ]
