# Generated by Django 5.1.3 on 2024-12-13 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_subscriptionplanduration_pre_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplanduration',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='Thời gian gói'),
        ),
        migrations.AlterField(
            model_name='subscriptionplanduration',
            name='pre_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giá gốc'),
        ),
        migrations.AlterField(
            model_name='subscriptionplanduration',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá hiện tại'),
        ),
        migrations.AlterField(
            model_name='subscriptionplanduration',
            name='subscription_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='durations', to='subscriptions.subscriptionplan', verbose_name='Kế hoạch'),
        ),
    ]
