# Generated by Django 5.1.3 on 2024-12-14 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_alter_subscriptionplanduration_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-id'], 'verbose_name': 'Nhóm tài khoản', 'verbose_name_plural': 'Nhóm tài khoản'},
        ),
        migrations.RemoveField(
            model_name='packagetoken',
            name='subscription_duration',
        ),
        migrations.AlterField(
            model_name='packagetoken',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.package', verbose_name='Nhóm tài khoản'),
        ),
    ]
