# Generated by Django 5.1.4 on 2024-12-17 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0005_remove_account_package_accountgroup'),
        ('subscriptions', '0015_alter_package_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagetoken',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforms.accountgroup', verbose_name='Nhóm tài khoản'),
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
