# Generated by Django 5.1.4 on 2024-12-17 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_alter_packagetoken_package_delete_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagetoken',
            old_name='package',
            new_name='account_group',
        ),
        migrations.AlterUniqueTogether(
            name='packagetoken',
            unique_together=set(),
        ),
    ]
