# Generated by Django 5.1.4 on 2024-12-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_rename_package_packagetoken_account_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagetoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày hết hạn'),
        ),
    ]
