# Generated by Django 5.1.4 on 2024-12-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0009_accountgroup_accounts'),
        ('subscriptions', '0018_alter_packagetoken_expires_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplanduration',
            options={'ordering': ['duration'], 'verbose_name': 'Bộ lọc thòi hạn gói', 'verbose_name_plural': 'Bộ lọc thòi hạn gói'},
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả gói'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='Cấp độ'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên gói'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='platforms',
            field=models.ManyToManyField(related_name='package_templates', to='platforms.platform', verbose_name='Các nền tảng trong gói'),
        ),
        migrations.CreateModel(
            name='SubscriptionDurationFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(verbose_name='Bộ lọc thời hạn (tháng)')),
                ('is_hot', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('subscription_durations', models.ManyToManyField(blank=True, related_name='groups', to='subscriptions.subscriptionplanduration', verbose_name='Thời hạn gói')),
            ],
        ),
    ]
