# Generated by Django 5.1.4 on 2024-12-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0019_alter_subscriptionplanduration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiondurationfilter',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Tên bộ lọc'),
            preserve_default=False,
        ),
    ]
