# Generated by Django 5.1.4 on 2024-12-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0020_subscriptiondurationfilter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='recommended',
            field=models.BooleanField(default=False, verbose_name='Đề xuất gói'),
        ),
    ]
