# Generated by Django 5.1.4 on 2024-12-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0021_subscriptionplan_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_trial',
            field=models.BooleanField(default=False, verbose_name='Gói thử nghiệm'),
        ),
    ]
