# Generated by Django 5.1.4 on 2024-12-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0022_subscriptionplan_is_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='level',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Thứ tự'),
        ),
    ]
