# Generated by Django 5.1.4 on 2024-12-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0023_alter_subscriptionplan_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptiondurationfilter',
            options={'ordering': ['duration'], 'verbose_name': 'Bộ lọc thòi hạn gói', 'verbose_name_plural': 'Bộ lọc thòi hạn gói'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplanduration',
            options={'ordering': ['duration'], 'verbose_name': 'Thời hạn gói', 'verbose_name_plural': 'Thời hạn gói'},
        ),
    ]
