# Generated by Django 5.1.4 on 2024-12-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0024_alter_subscriptiondurationfilter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='featrures',
            field=models.TextField(blank=True, default='', verbose_name='Tính năng'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả gói'),
        ),
    ]
