# Generated by Django 5.1.4 on 2024-12-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0025_subscriptionplan_featrures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiondurationfilter',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='Bộ lọc thời hạn (ngày)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplanduration',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='Thời gian gói (ngày)'),
        ),
    ]
