# Generated by Django 5.1.4 on 2024-12-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0026_alter_subscriptiondurationfilter_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_trial',
            field=models.BooleanField(default=False, verbose_name='Gói dùng thử'),
        ),
    ]
