# Generated by Django 5.1.3 on 2024-12-07 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Semrush', 'Semrush'), ('Keywords Tool', 'Keywords Tool'), ('Canva', 'Canva'), ('FreePik', 'Freepik'), ('Minea', 'Minea'), ('Placeit', 'Place It'), ('Pipi Ads', 'Pipi Ads'), ('Heyesty', 'Hey Esty'), ('Dropship', 'Dropship'), ('Auto DS', 'Auto Ds')], default='Semrush', max_length=100)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('logo_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('rented_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('rented_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rented_accounts', to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforms.platform')),
            ],
        ),
        migrations.CreateModel(
            name='AccountCookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforms.account')),
            ],
        ),
    ]
