# Generated by Django 5.1.3 on 2024-12-11 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
        ('subscriptions', '0007_remove_package_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='subscriptions.package'),
        ),
    ]
