# Generated by Django 5.1.4 on 2024-12-17 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0004_alter_platform_name'),
        ('subscriptions', '0015_alter_package_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='package',
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('max_users', models.PositiveIntegerField(default=10)),
                ('buyers', models.ManyToManyField(blank=True, related_name='bought_packages', to=settings.AUTH_USER_MODEL)),
                ('subscription_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_groups', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Nhóm tài khoản',
                'verbose_name_plural': 'Nhóm tài khoản',
                'ordering': ['-id'],
            },
        ),
    ]
