# Generated by Django 5.1.4 on 2024-12-18 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0005_remove_account_package_accountgroup'),
        ('subscriptions', '0017_rename_package_packagetoken_account_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountgroup',
            name='subscription_plan',
        ),
        migrations.AddField(
            model_name='accountgroup',
            name='subscription_duration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_groups', to='subscriptions.subscriptionplanduration'),
        ),
    ]
