# Generated by Django 5.1.4 on 2024-12-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0006_remove_accountgroup_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='login_with',
            field=models.CharField(choices=[('cookie', 'Cookie'), ('rankerfox', 'Rankerfox'), ('adspower', 'Ads Power')], default='cookie', max_length=255, verbose_name='Đăng nhập bằng'),
        ),
    ]
