# Generated by Django 5.1.4 on 2024-12-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0008_account_password_account_two_factor_auth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountgroup',
            name='accounts',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='platforms.account', verbose_name='Tài khoản trong nhóm'),
        ),
    ]
