# Generated by Django 5.1.4 on 2024-12-19 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0009_accountgroup_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='login_with',
        ),
    ]
