# Generated by Django 5.1.4 on 2024-12-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0010_remove_account_login_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Thời gian hết hạn (admin)',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='buyed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian mua (admin)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hết hạn (user)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='rented_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian mua (user)'),
        ),
    ]
