# Generated by Django 5.1.4 on 2024-12-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0011_account_thời_gian_hết_hạn_admin__account_buyed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Thời gian hết hạn (admin)',
        ),
        migrations.RemoveField(
            model_name='account',
            name='buyed_at',
        ),
        migrations.AddField(
            model_name='account',
            name='expiry_date',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hạn sử dụng tài khoản'),
        ),
    ]
