# Generated by Django 5.1.4 on 2024-12-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0013_platform_login_choice_alter_account_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='expiry_date',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hạn sử dụng tài khoản (admin) (ngày)'),
        ),
    ]
