# Generated by Django 5.1.4 on 2024-12-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0014_alter_account_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='login_choice',
            field=models.CharField(blank=True, choices=[('cookie', 'Cookie'), ('rankerfox', 'Rankerfox'), ('adspower', 'Ads Power'), ('spy', 'Spy Essentials')], default='cookie', max_length=255, null=True, verbose_name='Phương thức đăng nhập'),
        ),
    ]
