# Generated by Django 5.1.4 on 2024-12-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0015_alter_platform_login_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Giới thiệu gói'),
        ),
        migrations.AlterField(
            model_name='accountgroup',
            name='max_users',
            field=models.PositiveIntegerField(default=10, verbose_name='Giới hạn người dùng'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='description',
            field=models.TextField(verbose_name='Mô tả ngắn'),
        ),
    ]
