# Generated by Django 5.1.4 on 2024-12-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0016_platform_about_alter_accountgroup_max_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Mô tả ngắn'),
        ),
    ]
