# Generated by Django 5.1.4 on 2024-12-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0017_alter_platform_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='about',
        ),
        migrations.AddField(
            model_name='account',
            name='buy_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian mua (admin)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hết hạn (admin)'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Mô tả ngắn (Tối đa 500 từ)'),
        ),
    ]
