# Generated by Django 5.1.4 on 2024-12-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0018_remove_platform_about_account_buy_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='featrures',
            field=models.TextField(blank=True, default='', verbose_name='Tính năng'),
        ),
    ]
