# Generated by Django 5.1.3 on 2024-12-09 17:53

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0006_subscriptionplan_level_alter_packagetoken_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=orders.models.generate_payment_code, max_length=64, unique=True, verbose_name='Mã đơn hàng')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số tiền')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('paid', 'Đã thanh toán'), ('failed', 'Thất bại'), ('expired', 'Hết hạn')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.package', verbose_name='Gói')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplan', verbose_name='Kế hoạch đăng ký')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
        ),
    ]
