# Generated by Django 5.1.3 on 2024-12-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_is_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Chuyển khoản ngân hàng')], max_length=50, verbose_name='Phương thức thanh toán')),
                ('account_number', models.CharField(max_length=50, verbose_name='Số tài khoản')),
                ('bank_code', models.CharField(max_length=100, verbose_name='Mã ngân hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Cài đặt thanh toán',
                'verbose_name_plural': 'Cài đặt thanh toán',
            },
        ),
    ]
