# Generated by Django 5.1.3 on 2024-12-13 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options_paymentsetting_is_active'),
        ('subscriptions', '0014_alter_subscriptionplanduration_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subscription_duration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionplanduration', verbose_name='Thời hạn'),
        ),
    ]
