# Generated by Django 5.1.3 on 2024-12-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_alter_coupon_options_alter_coupon_code'),
        ('orders', '0006_alter_order_amount_alter_order_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='package',
        ),
        migrations.AddField(
            model_name='order',
            name='coupons',
            field=models.ManyToManyField(blank=True, related_name='orders', to='coupons.coupon', verbose_name='Mã giảm giá'),
        ),
    ]
