# Generated by Django 5.1.3 on 2024-12-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_alter_coupon_options_alter_coupon_code'),
        ('orders', '0008_order_transfer_amount_alter_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupons',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='coupons.coupon', verbose_name='Mã giảm giá'),
        ),
    ]
