# Generated by Django 5.1.3 on 2024-12-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá trị đơn hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transfer_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tiền nhận được'),
        ),
    ]
