# Generated by Django 5.1.4 on 2024-12-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_coupon_created_at_coupon_updated_at'),
        ('orders', '0011_alter_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupons',
            field=models.ManyToManyField(blank=True, related_name='orders', to='coupons.coupon', verbose_name='Mã giảm giá'),
        ),
    ]
