# Generated by Django 5.1.4 on 2024-12-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Đã sử dụng'),
        ),
    ]
