# Generated by Django 5.1.3 on 2024-11-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='blacklist_path',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='css_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='js_script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
