# Generated by Django 5.1.3 on 2024-12-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_share', '0006_alter_platform_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformaccount',
            name='login',
            field=models.TextField(blank=True, choices=[('Username/Password', 'Username Password'), ('Cookie', 'Cookie')], default='Username/Password', null=True, verbose_name='Đăng nhập bằng'),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='login_method',
            field=models.CharField(choices=[('Username/Password', 'Username Password'), ('Cookie', 'Cookie')], default='Username/Password', max_length=100),
        ),
    ]
